- name: checking the user
  hosts: frontend
  become: yes
  tasks:
  - name: getting user
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: checking info
    ansible.builtin.debug:
     msg: "user info: {{USER}}"
