- name: creating 
  hosts: localhost
  connection: local
  vars:
   vpc_subnet_id: subnet-07cb2872dc036f288
   instance_type: t2.micro
   security_group: sg-02885d0f240bf1152
   image_id: ami-09c813fb71547fc4f
   instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: creating servers
    amazon.aws.ec2_instance:
     name: "{{item}}"
     vpc_subnet_id: subnet-07cb2872dc036f288
     instance_type: t2.micro
     security_group: sg-02885d0f240bf1152
     image_id: ami-09c813fb71547fc4f
    loop: "{{instances}}"
    register: ec2

  - name: r53
    amazon.aws.route53:
     state: present
     zone: the4teen.info
     record: "{{item.item}}.the4teen.info"
     value: "{{item.instances[0].private_ip_address}}"
     type: A
     ttl: 1
     wait: true
    loop: "{{ec2.results}}"