- name: reading variable
  hosts: frontend
  vars_prompt:
  - name: name
    prompt: enter your name
  - class: studying
    prompt: what are you studying
  tasks:
  - name: asking at run time
    ansible.builtin.debug:
     msg: "Hello! Iam {{name}} currently {{studying}}"